# Generated by Django 4.1.6 on 2023-02-13 01:41

from django.db import migrations, models
import django.db.models.deletion
import kwork.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('kwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(default=kwork.helpers.generate_random_session_key, max_length=128, verbose_name='Ключ сессии')),
                ('authorized_at', models.DateTimeField(default=None, null=True, verbose_name='Время, в которое выполнена текущая авторизация')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_session', to='kwork.user')),
            ],
        ),
    ]
